force-app/main/default/objects/Work_Order_Files__c/Work_Order_Files__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the AWS S3 URL of image files uploaded by Field Service Technician from SFS Mobile app</description>
    <label>Work Order Files</label>
    <nameField>
        <displayFormat>WOF-{00000}</displayFormat>
        <label>Work Order Files Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Files__c/fields/AWS_S3_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>AWS_S3_Error_Message__c</fullName>
    <label>AWS S3 Error Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/AWS_S3_File_Path__c.field-meta.xml
<CustomField>
    <fullName>AWS_S3_File_Path__c</fullName>
    <label>AWS S3 File Path</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/AWS_S3_File_Upload_Status__c.field-meta.xml
<CustomField>
    <fullName>AWS_S3_File_Upload_Status__c</fullName>
    <label>AWS S3 File Upload Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocumentId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/File_Size__c.field-meta.xml
<CustomField>
    <fullName>File_Size__c</fullName>
    <label>File Size</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/Image_Type__c.field-meta.xml
<CustomField>
    <fullName>Image_Type__c</fullName>
    <label>Image Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repair Images</fullName>
            </value>
            <value>
                <fullName>Face Plate Images</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order_Files__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Work Order Files</relationshipLabel>
    <relationshipName>Work_Order_Files</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Wrap_Up__c.field-meta.xml
<CustomField>
    <fullName>Wrap_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wrap Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SFS_AWSFailedFileRetryBatch_Test.cls
/**
* @description       :
* @author            : Salesforce Services
* @group             :
* @last modified on  : 11-04-2020
* @last modified by  : Salesforce Services
* Modifications Log
* Ver   Date         Author                               Modification
* 1.0   11-02-2020   Vandana Verma                 Initial Version
**/
@isTest
public class SFS_AWSFailedFileRetryBatch_Test {
 
    
    @TestSetup
    static void setup(){
        NamedCredential namedCredential=[SELECT DeveloperName, Endpoint FROM NamedCredential where DeveloperName ='SFS_AWS_S3_Credentials' limit 1];
        
        //Create Parent Work Order
        WorkOrder workOrderRec = new WorkOrder();
        workOrderRec.Status = 'InProgress';
        workOrderRec.Wrap_Up__c = true;
        workOrderRec.Total_Due__c = 200;
        insert workOrderRec;
        system.debug('workOrderRec '+workOrderRec);
        //Creating Content Version record
        ContentVersion cv = new ContentVersion(Title = 'ABC',
                                               PathOnClient = 'test',
                                               VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body'),
                                               ReasonForChange = 'TestClassCoverage',
                                               Description='Test Image'
                                              );
        insert cv;
        system.debug('cv '+cv);
        ContentVersion version=[SELECT VersionData,Title,ContentDocumentId,FileExtension,FileType,Description FROM ContentVersion limit 1];
        
        String filename='Test Image';
        String versionData='test data to upload';
        String url = 'callout:'+namedCredential.DeveloperName+'/'+filename;
        string enpointURL=namedCredential.Endpoint+'/'+filename;
        Work_Order_Files__c  newobj=new Work_Order_Files__c();
        newobj.AWS_S3_File_Path__c =enpointURL;
        newobj.AWS_S3_File_Upload_Status__c ='Failure';
        newobj.AWS_S3_Error_Message__c ='Some error occured';
        newobj.Description__c  ='Test File';
        newobj.Image_Type__c  ='Repair images';
        newobj.Work_Order__c =workOrderRec.Id;
        newobj.ContentDocumentId__c = version.ContentDocumentId;
        newobj.File_Size__c =String.valueOf(versionData.length());
        insert newobj;
        system.debug('newobj '+newobj);
    }
    
    @isTest
    static void testMethod1() {
        Test.setMock(HttpCalloutMock.class, new HS_HttpUtilMockSuccess());
        Test.startTest();
        
        SFS_AWSFailedFileRetryBatch nextBatch = new SFS_AWSFailedFileRetryBatch();
        Database.executeBatch(nextBatch, 200);
        
        Test.stopTest();
        
    } 
    @isTest
    static void testMethod2() {
        Test.setMock(HttpCalloutMock.class, new HS_HttpUtilMockFailure());
        Test.startTest();
        
        SFS_AWSFailedFileRetryBatch nextBatch = new SFS_AWSFailedFileRetryBatch();
        Database.executeBatch(nextBatch, 200);
        
        Test.stopTest();
        
    } 
}