force-app/main/default/objects/RSO_PE__e/RSO_PE__e.object-meta.xml
<CustomObject>
    <label>RSO PE</label>
    <pluralLabel>RSO PE</pluralLabel>
</CustomObject>

force-app/main/default/objects/RSO_PE__e/fields/Resource_Id__c.field-meta.xml
<CustomField>
    <fullName>Resource_Id__c</fullName>
    <label>Resource Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSO_PE__e/fields/Scheduling_Policy__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Policy__c</fullName>
    <label>Scheduling Policy</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RSO_PE__e/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Assigned_Resource__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field stores the service resource scheduled to the service appointment</description>
    <label>Assigned Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SFS_ABRSO_PlatformEventTriggerHandler.cls
/**
 * Created by ayushmathur on 05/04/23.
 */

public with sharing class SFS_ABRSO_PlatformEventTriggerHandler implements rflib_TriggerHandler {
    private static final rflib_Logger LOGGER = rflib_LoggerUtil.getFactory().createLogger('SFS_ABRSO_PlatformEventTriggerHandler');
    public void run(rflib_TriggerManager.Args triggerArguments) {
        if (triggerArguments.operation.name() == SFS_ABConstantUtil.AFTER_INSERT) {
            LOGGER.info('CALLING AFTER Insert');
            invokeRSO(triggerArguments);
        }
    }
    public static void invokeRSO(rflib_TriggerManager.Args triggerArguments) {
        System.debug('Inside handler invokeRSO ');

        Map<Id,List<ServiceAppointment>> resourceIdToSAMap =new Map<Id, List<ServiceAppointment>>();
        Set<Id> requiredSaIds = new Set<Id>();
        Set<Id> candidatesIds = new Set<Id>();
        List<RSO_PE__e> rsoPes = (List<RSO_PE__e>) triggerArguments.newRecords;
        List<ServiceAppointment> futureAppointments=new List<ServiceAppointment>();
        Datetime startTime =rsoPes[0].StartTime__c;
        Datetime endTime = rsoPes[0].End_Time__c;
        Id customerFirstId = rsoPes[0].Scheduling_Policy__c;

        List<Id> resourceIds =new List<Id>();
        for(RSO_PE__e rsoEvent :rsoPes){
            resourceIds.add(rsoEvent.Resource_Id__c);
        }
        if(resourceIds.size()>0) {
            for (ServiceAppointment sa : [
                    SELECT Id, Assigned_Resource__c, FSL__Pinned__c,SchedStartTime
                    FROM ServiceAppointment
                    WHERE Assigned_Resource__c IN :resourceIds
                    AND SchedStartTime >= :startTime
                    AND SchedStartTime <= :endTime
            ]) {
                if (!resourceIdToSAMap.containsKey(sa.Assigned_Resource__c)) {
                    resourceIdToSAMap.put(sa.Assigned_Resource__c, new List<ServiceAppointment>());
                }
                resourceIdToSAMap.get(sa.Assigned_Resource__c).add(sa);
            }
System.debug('resourceIdToSAMap '+resourceIdToSAMap);
            for (Id resourceId : resourceIdToSAMap.keySet()) {
                System.debug('resourceIdToSAMap.keySet() '+resourceIdToSAMap.keySet());
                System.debug('resourceId '+resourceId);

                futureAppointments = resourceIdToSAMap.get(resourceId);
                if (futureAppointments.size() > 0) {
                    for (ServiceAppointment sa : futureAppointments) {
                        if (sa.SchedStartTime!=null) {
                            candidatesIds.add(sa.Id);
                            
                        } /*else {

                        }*/
                    }
/*
                    if (candidatesIds.size() > 0) {
*/
                        SFS_ABInvokeRSO.invokeRSO(resourceId, customerFirstId, startTime, endTime, candidatesIds, requiredSaIds);
                    /*}*/
                }
            }
        }
        }
    public void onConsecutiveRun(rflib_TriggerManager.Args args, Integer numInvocation) {
    }
}