force-app/main/default/objects/Serviceable_Postal_Code__c/Serviceable_Postal_Code__c.object-meta.xml
<CustomObject>
    <label>Serviceable Postal Code</label>
    <nameField>
        <displayFormat>SPC-{000}</displayFormat>
        <label>Serviceable Postal Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serviceable Postal Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serviceable_Postal_Code__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <referenceTo>Postal_Codes__c</referenceTo>
    <relationshipLabel>Serviceable Postal Codes</relationshipLabel>
    <relationshipName>Serviceable_Postal_Codes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serviceable_Postal_Code__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Serviceable Postal Codes</relationshipLabel>
    <relationshipName>Serviceable_Postal_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SFS_ABServicePostalCodeTriggerHandler.cls
public with sharing class SFS_ABServicePostalCodeTriggerHandler implements rflib_TriggerHandler {
    

    public void run(rflib_TriggerManager.Args args) {
        if (args.operation == System.TriggerOperation.BEFORE_INSERT) {
            preventDuplicatePostalCodes(args);
        }

        if (args.operation == System.TriggerOperation.AFTER_INSERT) {
        }

        if (args.operation == System.TriggerOperation.BEFORE_UPDATE) {
            preventDuplicatePostalCodes(args);
        }

        if (args.operation == System.TriggerOperation.AFTER_UPDATE) {
        }

        if (args.operation == System.TriggerOperation.BEFORE_DELETE) {
        }

        if (args.operation == System.TriggerOperation.AFTER_DELETE) {
        }
    }

    public static void preventDuplicatePostalCodes(rflib_TriggerManager.Args args){

        List<Serviceable_Postal_Code__c> newServiceablePostalCodeRecords = new List<Serviceable_Postal_Code__c>();
        if (args.operation == System.TriggerOperation.BEFORE_INSERT) {
            newServiceablePostalCodeRecords = (List<Serviceable_Postal_Code__c>) args.newRecords;
        }

        if (args.operation == System.TriggerOperation.BEFORE_UPDATE) {
            for (Serviceable_Postal_Code__c svcPostalRec : (List<Serviceable_Postal_Code__c>) args.newRecords) {
                Serviceable_Postal_Code__c oldSVCPostalRec = (Serviceable_Postal_Code__c) args.oldRecordsMap.get(svcPostalRec.Id);
                if (oldSVCPostalRec.Service_Resource__c != svcPostalRec.Service_Resource__c || oldSVCPostalRec.Postal_Code__c != svcPostalRec.Postal_Code__c ) {
                    newServiceablePostalCodeRecords.add(svcPostalRec);
                }
            }
        }

        Map<String, List<String>> svcResourceToPostalCodeMap = new Map<String, List<String>>();
        for (Serviceable_Postal_Code__c spcRec : newServiceablePostalCodeRecords) {
            if (!svcResourceToPostalCodeMap.containsKey(spcRec.Service_Resource__c)) {
                svcResourceToPostalCodeMap.put(spcRec.Service_Resource__c, new List<String>());
            }
            svcResourceToPostalCodeMap.get(spcRec.Service_Resource__c).add(spcRec.Postal_Code__c);
        }

        List<Serviceable_Postal_Code__c> existingServiceablePostalCodeList = [SELECT Id, Service_Resource__c, Postal_Code__c FROM Serviceable_Postal_Code__c WHERE Service_Resource__c IN : svcResourceToPostalCodeMap.keySet()];

        for (Serviceable_Postal_Code__c existingsvcPostalRec : existingServiceablePostalCodeList) {
            if (!svcResourceToPostalCodeMap.containsKey(existingsvcPostalRec.Service_Resource__c)) {
                svcResourceToPostalCodeMap.put(existingsvcPostalRec.Service_Resource__c, new List<String>());
            }
            svcResourceToPostalCodeMap.get(existingsvcPostalRec.Service_Resource__c).add(existingsvcPostalRec.Postal_Code__c);
        }

        for (Serviceable_Postal_Code__c spcRec : newServiceablePostalCodeRecords) {
            Integer dupliatePostalCodeInstance = 0;
            if (svcResourceToPostalCodeMap.containsKey(spcRec.Service_Resource__c)) {
                for (String postalCode : svcResourceToPostalCodeMap.get(spcRec.Service_Resource__c)) {
                    if (spcRec.Postal_Code__c == postalCode) {
                        dupliatePostalCodeInstance = dupliatePostalCodeInstance + 1;
                    }
                }
            }

            if (dupliatePostalCodeInstance > 1) {
                spcRec.addError('This Serviceable Postal Code has already been added to the Resource');
            }
        }
    }

    public void onConsecutiveRun(rflib_TriggerManager.Args args, Integer numInvocation) {
        return;
    }
}