force-app/main/default/objects/Capacity_Rebuild_Job__c/Capacity_Rebuild_Job__c.object-meta.xml
<CustomObject>
    <label>Capacity Rebuild Job</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Capacity Rebuild Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Rebuild Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capacity_Rebuild_Job__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Capacity Rebuild Jobs</relationshipLabel>
    <relationshipName>Capacity_Rebuild_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rebuild_Job__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Capacity Rebuild Jobs</relationshipLabel>
    <relationshipName>Capacity_Rebuild_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rebuild_Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Absence Delete</fullName>
            </value>
            <value>
                <fullName>Absence Insert</fullName>
            </value>
            <value>
                <fullName>Absence Update</fullName>
            </value>
            <value>
                <fullName>Capacity Template Delete</fullName>
            </value>
            <value>
                <fullName>Capacity Template Insert</fullName>
            </value>
            <value>
                <fullName>Capacity Template Update</fullName>
            </value>
            <value>
                <fullName>Resource Capacity Insert New Day</fullName>
            </value>
            <value>
                <fullName>Service Appointment Update</fullName>
            </value>
            <value>
                <fullName>Service Appointment Update No AR</fullName>
            </value>
            <value>
                <fullName>Service Resource Update</fullName>
            </value>
            <value>
                <fullName>Service Territory Member Delete</fullName>
            </value>
            <value>
                <fullName>Service Territory Member Insert</fullName>
            </value>
            <value>
                <fullName>Service Territory Member Update</fullName>
            </value>
            <value>
                <fullName>Service Territory Update</fullName>
            </value>
            <value>
                <fullName>Service Territory Update - With Resource</fullName>
            </value>
            <value>
                <fullName>Shift Delete</fullName>
            </value>
            <value>
                <fullName>Shift Insert</fullName>
            </value>
            <value>
                <fullName>Shift Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/Capacity_Rule_Template__c.object-meta.xml
<CustomObject>
    <label>Capacity Rule Template</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Capacity Rule Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Rule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency FFS</fullName>
            </value>
            <value>
                <fullName>Emergency MC</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Part Installs</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Repair FFS</fullName>
            </value>
            <value>
                <fullName>Repair MC</fullName>
            </value>
            <value>
                <fullName>TuneUpAC</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat FFS</fullName>
            </value>
            <value>
                <fullName>TuneUpsAC FFS</fullName>
            </value>
            <value>
                <fullName>Delayed Finish</fullName>
                <isActive>false</isActive>
                <label>Delayed Finish</label>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
                <isActive>false</isActive>
                <label>Delayed Start</label>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
                <isActive>false</isActive>
                <label>Due Date Approaching</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <isActive>false</isActive>
                <label>Low</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Repair</fullName>
                <isActive>false</isActive>
                <label>Repair</label>
            </value>
            <value>
                <fullName>VIP Work</fullName>
                <isActive>false</isActive>
                <label>VIP Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/Consumed_Capacity__c.object-meta.xml
<CustomObject>
    <label>Consumed Capacity</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Consumed Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumed Capacity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumed_Capacity__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(ISPICKVAL(Type__c, &apos;Daily Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before__c), NOW() + (Release_X_Hours_Before__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),IF(ISPICKVAL(Type__c, &apos;Rule Based Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before_Rule__c) ,NOW() + (Release_X_Hours_Before_Rule__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),true))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Date__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Date__c</fullName>
    <label>Capacity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/IsOverridden__c.field-meta.xml
<CustomField>
    <fullName>IsOverridden__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsOverridden</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSL__Efficiency__c.field-meta.xml
<CustomField>
    <fullName>FSL__Efficiency__c</fullName>
    <label>Efficiency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/SFS_AB_Capacity_Settings__mdt.object-meta.xml
<CustomObject>
    <label>SFS AB Capacity Settings</label>
    <pluralLabel>SFS AB Capacity Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFS_ABCapacityRebuildJobUtil.cls
/**
 * @description       : To Capacity Rebuild Job data for any change related to Resource and Territory
 * @author            : Salesforce Services
 * @group             :
 * @last modified on  : 06-14-2021
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   05-08-2021   Salesforce Services       Initial Version
 **/

public class SFS_ABCapacityRebuildJobUtil {
    final static string DAYS_TO_BUILD_CAPACITY = 'Days_to_Build_Capacity_Data';
    // Calculate default last date
    static SFS_AB_Capacity_Settings__mdt appConfig = [
        SELECT Id, Configuration_Name__c, Configuration_Value__c
        FROM SFS_AB_Capacity_Settings__mdt
        WHERE Configuration_Name__c = :DAYS_TO_BUILD_CAPACITY
    ];
    static Integer daysToBuild = Integer.valueOf(appConfig.Configuration_Value__c);
    static Date maxDate = System.Today().addDays(daysToBuild);

    //static method to create a single Capacity rebuild Job record
    public static Capacity_Rebuild_Job__c createCapacityRebuildJobRecord(String type, Id serviceResourceId, Id serviceTerritoryId, Date startDate, Date endDate) {
        Capacity_Rebuild_Job__c capacityRebuildJobRecord = new Capacity_Rebuild_Job__c();
        capacityRebuildJobRecord.Type__c = type;
        if (String.isNotBlank(serviceResourceId)) {
            capacityRebuildJobRecord.Service_Resource__c = serviceResourceId;
        }
        if (String.isNotBlank(serviceTerritoryId)) {
            capacityRebuildJobRecord.Service_Territory__c = serviceTerritoryId;
        }
        if (startDate != null) {
            capacityRebuildJobRecord.Start_Date__c = startDate;
        }
        if (endDate != null) {
            capacityRebuildJobRecord.End_Date__c = endDate;
        }

        return capacityRebuildJobRecord;
    }

    //Get STM records for a Service Resource ids and/or Service Territory Ids
    public static List<ServiceTerritoryMember> getSTMListById(Set<Id> serviceResourceIdSet, Set<Id> serviceterritoryIdSet) {
        System.debug('getSTMListById.serviceResourceIdSet>>' + serviceResourceIdSet);
        System.debug('getSTMListById.serviceterritoryIdSet>>' + serviceterritoryIdSet);

        List<ServiceTerritoryMember> stmList = new List<ServiceTerritoryMember>();

        if (serviceResourceIdSet != null && serviceterritoryIdSet == null) {
            System.debug('getSTMListById 1>');
            stmList = [
                SELECT
                    Id,
                    ServiceResourceId,
                    ServiceTerritoryId,
                    TerritoryType,
                    ServiceResource.FSL__Efficiency__c,
                    OperatingHoursId,
                    EffectiveStartDate,
                    EffectiveEndDate,
                    ServiceTerritory.OperatingHoursId,
                    ServiceTerritory.OperatingHours.TimeZone
                FROM ServiceTerritoryMember
                WHERE ServiceResourceId IN :serviceResourceIdSet AND EffectiveStartDate <= :maxDate AND (EffectiveEndDate >= TODAY OR EffectiveEndDate = NULL)
                ORDER BY ServiceResourceId
            ];
            return stmList;
        } else if (serviceResourceIdSet == null && serviceterritoryIdSet != null) {
            System.debug('getSTMListById 2>');

            stmList = [
                SELECT
                    Id,
                    ServiceResourceId,
                    ServiceTerritoryId,
                    TerritoryType,
                    EffectiveStartDate,
                    EffectiveEndDate,
                    ServiceResource.FSL__Efficiency__c,
                    OperatingHoursId,
                    ServiceTerritory.OperatingHoursId,
                    ServiceTerritory.OperatingHours.TimeZone
                FROM ServiceTerritoryMember
                WHERE ServiceTerritoryId IN :serviceterritoryIdSet AND EffectiveStartDate <= :maxDate AND (EffectiveEndDate >= TODAY OR EffectiveEndDate = NULL)
                ORDER BY ServiceResourceId
            ];
            return stmList;
        } else if (serviceResourceIdSet != null && serviceterritoryIdSet != null) {
            System.debug('getSTMListById 3>');

            stmList = [
                SELECT
                    Id,
                    ServiceResourceId,
                    ServiceTerritoryId,
                    TerritoryType,
                    EffectiveStartDate,
                    EffectiveEndDate,
                    ServiceResource.FSL__Efficiency__c,
                    OperatingHoursId,
                    ServiceTerritory.OperatingHoursId,
                    ServiceTerritory.OperatingHours.TimeZone
                FROM ServiceTerritoryMember
                WHERE
                    ServiceTerritoryId IN :serviceterritoryIdSet
                    AND ServiceResourceId = :serviceResourceIdSet
                    AND EffectiveStartDate <= :maxDate
                    AND (EffectiveEndDate >= TODAY
                    OR EffectiveEndDate = NULL)
                ORDER BY ServiceResourceId
            ];
            return stmList;
        } else {
            return null;
        }
    }

    //Wrapper class to hold the data required for capacity calculation of the resource
    public class CreateCapacityRebuildDataMapWrapper {
        public Date minDate;
        public Date maxDate;
        public Map<Id, SFS_ABCapacityRebuildJobBatch.rebuildDate> recordIdToDateMap = new Map<Id, SFS_ABCapacityRebuildJobBatch.rebuildDate>();
    }

    //This method will create and return the createCapacityRebuildDataMapWrapper to process the capacity calculation for the Resource
    public static CreateCapacityRebuildDataMapWrapper getCapacityRebuildDataMap(Id recordId, Date startDate, Date EndDate) {
        createCapacityRebuildDataMapWrapper recordIdToDateMapWrapper = new createCapacityRebuildDataMapWrapper();
        if (startDate < System.TODAY()) {
            startDate = recordIdToDateMapWrapper.minDate = System.today();
        } else {
            recordIdToDateMapWrapper.minDate = startDate;
        }
        if (EndDate == null) {
            EndDate = recordIdToDateMapWrapper.maxDate = maxDate;
        } else if (startDate == EndDate) {
            EndDate = recordIdToDateMapWrapper.maxDate = startDate;
        } else {
            EndDate = recordIdToDateMapWrapper.maxDate = EndDate;
        }
        System.debug('recordIdToDateMapWrapper:' + recordIdToDateMapWrapper);
        recordIdToDateMapWrapper.recordIdToDateMap.put(recordId, new SFS_ABCapacityRebuildJobBatch.rebuildDate(startDate, endDate));
        return recordIdToDateMapWrapper;
    }

    //This method will return the Consumed Capacity list for the resource
    public static List<Consumed_Capacity__c> getConsumedCapacity(String territoryId, Date startDate, Date endDate) {
        System.debug('getConsumedCapacity>> ');
        System.debug('territoryId>> ' + territoryId);
        System.debug('startDate>> ' + startDate);
        System.debug('endDate>> ' + endDate);
        if (territoryId != null) {
            return [
                SELECT
                    Id,
                    Capacity_Date__c,
                    Active__c,
                    Field__c,
                    Capacity_Rule_Template__c,
                    External_Id__c,
                    IsOverridden__c,
                    Max__c,
                    Max_Rule__c,
                    Object__c,
                    Overall_Capacity__c,
                    Overall_Capacity_Rule__c,
                    Overall_Consumption__c,
                    Parent_Consumed_Capacity__c,
                    Release_X_Hours_Before__c,
                    Release_X_Hours_Before_Rule__c,
                    Parent_Consumed_Capacity__r.Overall_Capacity__c,
                    Rule_Consumption__c,
                    Service_Territory__c,
                    Type__c,
                    Value__c,
					Slots__c
                FROM Consumed_Capacity__c
                WHERE Service_Territory__c = :territoryId 
				AND Capacity_Date__c >= :startDate AND Capacity_Date__c <= :endDate
                ORDER BY Type__c
            ];
        } else {
            return null;
        }
    }
}