force-app/main/default/objects/Overtime_Offers__c/Overtime_Offers__c.object-meta.xml
<CustomObject>
    <label>Resource Overtime Offer</label>
    <nameField>
        <displayFormat>OA-{00000}</displayFormat>
        <label>Resource Overtime Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Overtime Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Overtime_Offers__c/fields/Local_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Local_End_Time__c</fullName>
    <label>Local End Time</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Overtime_Offers__c/fields/Local_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Local_Start_Time__c</fullName>
    <label>Local Start Time</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Overtime_Offers__c/fields/Offer_Finish_Time__c.field-meta.xml
<CustomField>
    <fullName>Offer_Finish_Time__c</fullName>
    <label>Offer Finish Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Overtime_Offers__c/fields/Offer_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Offer_Start_Time__c</fullName>
    <label>Offer Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Overtime_Offers__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipName>Service_Resource_Overtime_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Overtime_Offers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Not Hired</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shift/fields/Local_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Local_End_Time__c</fullName>
    <label>Local End Time</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shift/fields/Local_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Local_Start_Time__c</fullName>
    <label>Local Start Time</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contact_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile_Number__c</fullName>
    <label>Contact Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ViewingRecordsOnMobileHelper.cls
public with sharing class ViewingRecordsOnMobileHelper {

    public Static Final Map<Integer, String> monthOfYear = new Map<Integer, String>{
        1 => 'Jan',
        2 => 'Feb',
        3 => 'Mar',
        4 => 'Apr',
        5 => 'May',
        6 => 'Jun',
        7 => 'Jul',
        8 => 'Aug',
        9 => 'Sep',
        10 => 'Oct',
        11 => 'Nov',
        12 => 'Dec'
    };

    @AuraEnabled(cacheable=true)
    public static List<Wrapper> getOvertimeOffersList(String userId){
        system.debug('request here: ');
        List<Wrapper> wrapperListToReturn = new List<Wrapper>();
        for(Overtime_Offers__c overTime : [SELECT Id, Offer_Start_Time__c, Offer_Finish_Time__c, Status__c, Comment__c, Local_Start_Time__c, Local_End_Time__c FROM Overtime_Offers__c WHERE Service_Resource__r.RelatedRecordId =: userId ORDER BY Local_Start_Time__c DESC]){
            Wrapper wrap = new Wrapper();
            wrap.id = overTime.Id;
            wrap.label = overTime.Local_Start_Time__c + ' : ' + overTime.Status__c;
            wrap.OfferStartTime = overTime.Offer_Start_Time__c;
            wrap.OfferFinishTime = overTime.Offer_Finish_Time__c;
            wrap.status = overTime.Status__c;
            wrap.comment = overTime.Comment__c;
            wrap.localStartDateTime = overTime.Local_Start_Time__c;
            wrap.localFinishDateTime = overTime.Local_End_Time__c;
            if(overTime.Status__c == 'Offered' || overTime.Status__c == 'Recalled'){
                wrap.isDisabled = false;
            }
            else{
                wrap.isDisabled = true;
            }
            wrapperListToReturn.add(wrap);
        }
        return wrapperListToReturn;
    }

    @AuraEnabled(cacheable=true)
    public static List<ShiftWrapper> getShiftsList(String userId){
        List<ShiftWrapper> wrapperListToReturn = new List<ShiftWrapper>();
        Datetime currentDatetime = DateTime.newInstance(system.today(), Time.newInstance(0, 0, 0, 0));
        Datetime after7DaysDatetime = DateTime.newInstance(system.today().addDays(7), Time.newInstance(23, 59, 0, 0));
        List<Shift> shiftListToResturn = [SELECT Id, ShiftNumber, StartTime, EndTime, Status, Local_Start_Time__c, Local_End_Time__c FROM Shift WHERE ServiceResource.RelatedRecordId =: userId AND StartTime >=: currentDatetime AND StartTime <=: after7DaysDatetime AND Status = 'Confirmed' ORDER BY StartTime ASC];
        for(Shift shiftRec : shiftListToResturn){
            ShiftWrapper shiftWrap = new ShiftWrapper();
            shiftWrap.id = shiftRec.Id;
            shiftWrap.shiftNumber = shiftRec.ShiftNumber;
            shiftWrap.status = shiftRec.Status;
            shiftWrap.startDate = convertDateTimeFormat(shiftRec.StartTime);
            shiftWrap.endDate = convertDateTimeFormat(shiftRec.EndTime);
            wrapperListToReturn.add(shiftWrap);
        }
        return wrapperListToReturn;
    }

    public static String convertDateTimeFormat(Datetime dateToFormat){
        String formatedDatetime = monthOfYear.get(dateToFormat.month()) + ' ' + String.valueOf(dateToFormat.day()) + ', ' + String.valueOf(dateToFormat.year()) + ' ';
        if(dateToFormat.hour() > 12){
            formatedDatetime = formatedDatetime + String.valueOf(dateToFormat.hour() - 12) + ':' + (String.valueOf(dateToFormat.minute()).length() == 1 ? '0' + String.valueOf(dateToFormat.minute()) : String.valueOf(dateToFormat.minute()));
        }
        else{
            formatedDatetime = formatedDatetime + String.valueOf(dateToFormat.hour()) + ':' + (String.valueOf(dateToFormat.minute()).length() == 1 ? '0' + String.valueOf(dateToFormat.minute()) : String.valueOf(dateToFormat.minute()));
        }
        if(dateToFormat.hour() > 11){
            formatedDatetime = formatedDatetime + ' PM';
        }
        else{
            formatedDatetime = formatedDatetime + ' AM';
        }
		return formatedDatetime;
    }

    @AuraEnabled(cacheable=true)
    public static String getServiceResource(String userId){
        ServiceResource svcresource = [SELECT Id FROM ServiceResource WHERE RelatedRecordId =: userId LIMIT 1];
        return svcresource.Id;
    }

    @AuraEnabled(cacheable=true)
    public static WorkOrder getWorkOrder(String recordId){
        WorkOrder workOrderRec = [SELECT Id, Contact_Phone_Number__c, Contact_Mobile_Number__c FROM WorkOrder WHERE Id =: recordId LIMIT 1];
        return workOrderRec;
    }

    public class Wrapper{
        @AuraEnabled
        public String id {get; set;}
        @AuraEnabled
        public String label {get; set;}
        @AuraEnabled
        public Datetime OfferStartTime {get; set;}
        @AuraEnabled
        public Datetime OfferFinishTime {get; set;}
        @AuraEnabled
        public String status {get; set;} 
        @AuraEnabled
        public String comment {get; set;} 
        @AuraEnabled
        public String localStartDateTime {get; set;} 
        @AuraEnabled
        public String localFinishDateTime {get; set;}
        @AuraEnabled
        public Boolean isDisabled {get; set;} 
    }

    public class ShiftWrapper{
        @AuraEnabled
        public String id {get; set;}
        @AuraEnabled
        public String startDate {get; set;}
        @AuraEnabled
        public String endDate {get; set;}
        @AuraEnabled
        public String shiftNumber {get; set;} 
        @AuraEnabled
        public String status {get; set;} 
    }
}