force-app/main/default/objects/Capacity_Rule_Template__c/Capacity_Rule_Template__c.object-meta.xml
<CustomObject>
    <label>Capacity Rule Template</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Capacity Rule Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Rule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Parent_Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency FFS</fullName>
            </value>
            <value>
                <fullName>Emergency MC</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Part Installs</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Repair FFS</fullName>
            </value>
            <value>
                <fullName>Repair MC</fullName>
            </value>
            <value>
                <fullName>TuneUpAC</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat FFS</fullName>
            </value>
            <value>
                <fullName>TuneUpsAC FFS</fullName>
            </value>
            <value>
                <fullName>Delayed Finish</fullName>
                <isActive>false</isActive>
                <label>Delayed Finish</label>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
                <isActive>false</isActive>
                <label>Delayed Start</label>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
                <isActive>false</isActive>
                <label>Due Date Approaching</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <isActive>false</isActive>
                <label>Low</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Repair</fullName>
                <isActive>false</isActive>
                <label>Repair</label>
            </value>
            <value>
                <fullName>VIP Work</fullName>
                <isActive>false</isActive>
                <label>VIP Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/recordTypes/Daily_Capacity_Template.recordType-meta.xml
<RecordType>
    <fullName>Daily_Capacity_Template</fullName>
    <active>true</active>
    <description>Create a Daily Capacity Template record</description>
    <label>Daily Capacity</label>
</RecordType>

force-app/main/default/objects/Consumed_Capacity__c/Consumed_Capacity__c.object-meta.xml
<CustomObject>
    <label>Consumed Capacity</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Consumed Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumed Capacity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumed_Capacity__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(ISPICKVAL(Type__c, &apos;Daily Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before__c), NOW() + (Release_X_Hours_Before__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),IF(ISPICKVAL(Type__c, &apos;Rule Based Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before_Rule__c) ,NOW() + (Release_X_Hours_Before_Rule__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),true))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Date__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Date__c</fullName>
    <label>Capacity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Overall_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Overall_Capacity__c</fullName>
    <label>Overall Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Overall_Capacity_Rule__c.field-meta.xml
<CustomField>
    <fullName>Overall_Capacity_Rule__c</fullName>
    <label>Overall Capacity (Rule)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Overall_Consumption__c.field-meta.xml
<CustomField>
    <fullName>Overall_Consumption__c</fullName>
    <label>Overall Consumption</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Parent_Consumed_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Consumed_Capacity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Consumed Capacity</label>
    <referenceTo>Consumed_Capacity__c</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Rule_Consumption__c.field-meta.xml
<CustomField>
    <fullName>Rule_Consumption__c</fullName>
    <label>Rule Consumption</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Work_Type_Category__c.field-meta.xml
<CustomField>
    <fullName>Work_Type_Category__c</fullName>
    <formula>TEXT(WorkType.Work_Type_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Type Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/FSL__Efficiency__c.field-meta.xml
<CustomField>
    <fullName>FSL__Efficiency__c</fullName>
    <label>Efficiency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/AvailableSlots.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8:00AM - 12:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00PM - 4:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00PM - 8:30PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30PM - 10:30PM</fullName>
    </customValue>
    <masterLabel>AvailableSlots</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SFS_ABTestFactory.cls
public with sharing class SFS_ABTestFactory {
    public SFS_ABTestFactory() {
    }

    public static final string TEST_USER_NAME1 = 'test_service_user@test.com';

    // Creating an test service resource user
    public static User createAServiceUser() {
        // Get the Profile for System Admin profile
        integer STRING_LENGTH = 3;
        Double MAX = Math.pow(10, STRING_LENGTH) - 1; // Returns 999
        String aleaNumberN = String.valueOf(Math.Round(Math.Random() * MAX)).leftPad(STRING_LENGTH, '0');
        Profile servicesProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User testServiceUser = new User();
        testServiceUser.FirstName = 'Test';
        testServiceUser.LastName = 'Service Resource';
        testServiceUser.ProfileId = servicesProfile.Id;
        testServiceUser.username = TEST_USER_NAME1 + aleaNumberN;
        testServiceUser.email = 'TestServiceUser@test.com' + aleaNumberN;
        testServiceUser.Alias = '02' + aleaNumberN;
        testServiceUser.AboutMe = SFS_ABConstantUtil.TEST_SR_GUID;
        testServiceUser.TimeZoneSidKey = 'GMT';
        testServiceUser.LocaleSidKey = 'en_US';
        testServiceUser.EmailEncodingKey = 'UTF-8';
        testServiceUser.LanguageLocaleKey = 'en_US';
        testServiceUser.IsActive = true;
        testServiceUser.FederationIdentifier = 'test5136131686851' + aleaNumberN;
        insert testServiceUser;
        return testServiceUser;
    }

    // Creating an test service resource user
    public static User createAServiceUser2(String UserName) {
        // Get the Profile for System Admin profile
        Profile servicesProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User testServiceUser = new User();
        testServiceUser.FirstName = 'Test';
        testServiceUser.LastName = 'Service Resource';
        testServiceUser.ProfileId = servicesProfile.Id;
        testServiceUser.username = UserName;
        testServiceUser.email = UserName;
        testServiceUser.Alias = '2222202';
        testServiceUser.TimeZoneSidKey = 'GMT';
        testServiceUser.LocaleSidKey = 'en_US';
        testServiceUser.EmailEncodingKey = 'UTF-8';
        testServiceUser.LanguageLocaleKey = 'en_US';
        testServiceUser.IsActive = true;
        testServiceUser.FederationIdentifier = UserName; //'test666666666668131686851';
        insert testServiceUser;
        return testServiceUser;
    }


    // Creating Contractor Account relationship data
    public static List<Capacity_Rule_Template__c> createDailyCapacityTemplates(String territoryId) {
        List<String> weekDays = new List<String>{ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' };
        List<Capacity_Rule_Template__c> rules = new List<Capacity_Rule_Template__c>();
        if (territoryId != null) {
            rules = [SELECT Id, Day_Of_Week__c FROM Capacity_Rule_Template__c WHERE Service_Territory__c = :territoryId];
        }

        if (rules.size() == 0) {
            for (String day : weekDays) {
                Capacity_Rule_Template__c rule = new Capacity_Rule_Template__c();
                rule.RecordTypeId = SFS_ABConstantUtil.DAILY_CAPACITY_TEMPLATE;
                rule.Day_Of_Week__c = day;
                rule.Active__c = true;
                rule.Max__c = 90;
                rule.Max_Rule__c = 33;
                rule.Active__c = true;
                rule.Type__c = 'Daily Capacity';
                if (territoryId != null) {
                    rule.Service_Territory__c = territoryId;
                }  
                rules.add(rule);
            }
            insert rules;
        }
        return rules;
    }

    // Creating Contractor Account relationship data
    public static List<Capacity_Rule_Template__c> createRuleBasedCapacityTemplates(List<Capacity_Rule_Template__c> dailyTemplates, String territoryId) {
        List<Capacity_Rule_Template__c> childRules = new List<Capacity_Rule_Template__c>();
        for (Capacity_Rule_Template__c dailyTemplate : dailyTemplates) {
            Capacity_Rule_Template__c template = new Capacity_Rule_Template__c();
            template.RecordTypeId = SFS_ABConstantUtil.RULE_BASED_CAPACITY_TEMPLATE;
            template.Object__c = 'ServiceAppointment';
            template.Field__c = 'Work_Type_Category__c';
            template.Value__c = 'Repair FFS';
            template.Max_Rule__c = 20;
            template.Active__c = true;
            template.Day_Of_Week__c = dailyTemplate.Day_Of_Week__c;
            template.Parent_Capacity_Rule_Template__c = dailyTemplate.Id;
            if (territoryId != null) {
                template.Service_Territory__c = territoryId;
            }  
            template.Type__c = 'Rule Based Capacity';
            childRules.add(template);
        }
        insert childRules;
        return childRules;
    }

    // Creating Service Resource data
    public static ServiceResource createServiceResource(User userRecord) {
        ServiceResource srRecord = new ServiceResource();
        srRecord.Name = (String.isBlank(userRecord.FirstName) ? '' : userRecord.FirstName + ' ') + userRecord.LastName;
        srRecord.IsActive = true;
        srRecord.RelatedRecordId = userRecord.Id;
        srRecord.ResourceType = 'T';
        srRecord.FSL__Efficiency__c = 1;
        //srRecord.Organization__c = organizationAccount.Id;
        //srRecord.SubContractor__c = contractorAccount.Id;
        insert srRecord;
        return srRecord;
    }


    // Creating WorkOrder data
    public static WorkOrder createWorkOrder() {
        WorkOrder workOrder = new WorkOrder();
        //workOrder.OrganizationAccount__c =  OrgnizationId;
        //workOrder.Sub_Contractor__c = subContractor1.Id;
        //workOrder.AccountId = personAccount.Id;
        integer STRING_LENGTH = 3;
        Double MAX = Math.pow(10, STRING_LENGTH) - 1; // Returns 999
        String aleaNumberN = String.valueOf(Math.Round(Math.Random() * MAX)).leftPad(STRING_LENGTH, '0');
        //workOrder.EdgeID__c = '194' + Integer.ValueOf(aleaNumberN);
        insert workOrder;
        return workOrder;
    }

    public static ServiceTerritory createServiceTerritory(String terrName) {
        OperatingHours testHours = createOperatingHours();
        insert testHours;
        OperatingHours tmpHours = [SELECT Id FROM OperatingHours WHERE Name = 'tstHours' LIMIT 1];

        ServiceTerritory testTerritory = new ServiceTerritory();
        testTerritory.Name = terrName;
        testTerritory.OperatingHoursId = tmpHours.Id;
        testTerritory.IsActive = true;

        insert testTerritory;

        return testTerritory;
    }

    // Creating ServiceTerritoryMember Data
    public static ServiceTerritoryMember createServiceTerritoryMember(ServiceResource srRecord, ServiceTerritory srTerritoryRecord) {
        ServiceTerritory tmpTerr = [SELECT Id FROM ServiceTerritory WHERE Name = :srTerritoryRecord.Name LIMIT 1];

        ServiceTerritoryMember stMemberRecord = new ServiceTerritoryMember();
        stMemberRecord.TerritoryType = 'P';
        stMemberRecord.ServiceTerritoryId = tmpTerr.Id;
        stMemberRecord.ServiceResourceId = srRecord.Id;
        stMemberRecord.EffectiveStartDate = System.now() - 1;
        stMemberRecord.EffectiveEndDate = System.now().addDays(5);
        insert stMemberRecord;
        ServiceTerritoryMember serviceTerritoryMemberRecord = [SELECT Id, ServiceTerritoryId, TerritoryType FROM ServiceTerritoryMember LIMIT 1];

        return serviceTerritoryMemberRecord;
    }

    public static OperatingHours createOperatingHours() {
        OperatingHours testHours = new OperatingHours(Name = 'tstHours');

        return testHours;
    }

    public static Consumed_Capacity__c createConsumedCapacity(Capacity_Rule_Template__c ruleTemplateRecord, String serviceTerritoryId, String type, Date capacityDate, Consumed_Capacity__c parentConsumedCapacity) {
        Consumed_Capacity__c capacity = new Consumed_Capacity__c();
        capacity.Capacity_Date__c = capacityDate;
        capacity.Service_Territory__c = serviceTerritoryId;
        capacity.Capacity_Rule_Template__c = ruleTemplateRecord.Id;
        capacity.Slots__c = ruleTemplateRecord.Slots__c;
        if (type == 'Daily Capacity') {
            capacity.RecordTypeId = SFS_ABConstantUtil.DAILY_CONSUMED_CAPACITY;
            capacity.Type__c = type;
            capacity.Max__c = 100;
            capacity.Overall_Capacity__c = 0;
            capacity.Overall_Consumption__c = 0;
            capacity.External_Id__c = ruleTemplateRecord.Service_Territory__c + '-' + capacityDate.format()+'-'+ ruleTemplateRecord.Slots__c+ '-' + 'Daily-Capacity';
        } else if (type == 'Rule Based Capacity') {
            capacity.RecordTypeId = SFS_ABConstantUtil.RULE_BASED_CONSUMED_CAPACITY;
            capacity.Type__c = type;
            capacity.Max_Rule__c = 50;
            capacity.Object__c = 'ServiceAppointment';
            capacity.Field__c = 'Work_Type_Category__c	';
            capacity.Value__c = 'Installation';
            capacity.Parent_Consumed_Capacity__c = parentConsumedCapacity.Id;
            capacity.Overall_Capacity_Rule__c = 0;
            capacity.Rule_Consumption__c = 0;
            capacity.External_Id__c = parentConsumedCapacity.Id + '__' + ruleTemplateRecord.Id+'__'+ruleTemplateRecord.Day_of_Week__c+'__'+ruleTemplateRecord.Value__c+'__'+ parentConsumedCapacity.Capacity_Date__c.format()+'__'+parentConsumedCapacity.Slots__c;
        }
        return capacity;
    }

    public static Capacity_Rule_Template__c createConsumedCapacityTemplate(String serviceTerritoryId, String dayOfTheWeek, String type, String slot, String parentConsumedCapacityTemplateId) {
        Capacity_Rule_Template__c template = new Capacity_Rule_Template__c();
        template.Service_Territory__c = serviceTerritoryId;
        template.Day_of_Week__c = dayOfTheWeek;
        template.Active__c = true;
        template.Slots__c = slot;
        if (type == 'Daily Capacity') {
            template.RecordTypeId = SFS_ABConstantUtil.DAILY_CAPACITY_TEMPLATE;
            template.Type__c = type;
            template.Max__c = 100;
        } else if (type == 'Rule Based Capacity') {
            template.RecordTypeId = SFS_ABConstantUtil.RULE_BASED_CAPACITY_TEMPLATE;
            template.Type__c = type;
            template.Max_Rule__c = 50;
            template.Object__c = 'ServiceAppointment';
            template.Field__c = 'Work_Type_Category__c	';
            template.Value__c = 'Installation';
            template.Parent_Capacity_Rule_Template__c = parentConsumedCapacityTemplateId;
        }
        return template;
    }
}