force-app/main/default/objects/Capacity_Rule_Template__c/Capacity_Rule_Template__c.object-meta.xml
<CustomObject>
    <label>Capacity Rule Template</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Capacity Rule Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Rule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Parent_Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Release_X_Hours_Before__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before__c</fullName>
    <label>Release X Hours Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Release_X_Hours_Before_Rule__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before_Rule__c</fullName>
    <label>Release X Hours Before (Rule)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency FFS</fullName>
            </value>
            <value>
                <fullName>Emergency MC</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Part Installs</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Repair FFS</fullName>
            </value>
            <value>
                <fullName>Repair MC</fullName>
            </value>
            <value>
                <fullName>TuneUpAC</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat FFS</fullName>
            </value>
            <value>
                <fullName>TuneUpsAC FFS</fullName>
            </value>
            <value>
                <fullName>Delayed Finish</fullName>
                <isActive>false</isActive>
                <label>Delayed Finish</label>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
                <isActive>false</isActive>
                <label>Delayed Start</label>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
                <isActive>false</isActive>
                <label>Due Date Approaching</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <isActive>false</isActive>
                <label>Low</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Repair</fullName>
                <isActive>false</isActive>
                <label>Repair</label>
            </value>
            <value>
                <fullName>VIP Work</fullName>
                <isActive>false</isActive>
                <label>VIP Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/Consumed_Capacity__c.object-meta.xml
<CustomObject>
    <label>Consumed Capacity</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Consumed Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumed Capacity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumed_Capacity__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(ISPICKVAL(Type__c, &apos;Daily Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before__c), NOW() + (Release_X_Hours_Before__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),IF(ISPICKVAL(Type__c, &apos;Rule Based Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before_Rule__c) ,NOW() + (Release_X_Hours_Before_Rule__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),true))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Date__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Date__c</fullName>
    <label>Capacity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Overall_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Overall_Capacity__c</fullName>
    <label>Overall Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Release_X_Hours_Before__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before__c</fullName>
    <label>Release X Hours Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Release_X_Hours_Before_Rule__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before_Rule__c</fullName>
    <label>Release X Hours Before (Rule)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/recordTypes/Rule_Based_Capacity.recordType-meta.xml
<RecordType>
    <fullName>Rule_Based_Capacity</fullName>
    <active>true</active>
    <description>Create a Rule Based Consumed Capacity record</description>
    <label>Rule Based Capacity</label>
</RecordType>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/SFS_AB_Capacity_Settings__mdt.object-meta.xml
<CustomObject>
    <label>SFS AB Capacity Settings</label>
    <pluralLabel>SFS AB Capacity Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/AvailableSlots.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8:00AM - 12:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00PM - 4:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00PM - 8:30PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30PM - 10:30PM</fullName>
    </customValue>
    <masterLabel>AvailableSlots</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SFS_ABNewDayBatchRuleConsumedCapacity.cls
/**
 * @description       : To Created Rule based CC records based on Rule based Capacity_Rule_Template__c records
 * @author            : Salesforce Services
 * @group             :
 * @last modified on  : 06-30-2021
 * Modifications Log
 * Ver   Date         Author                 Modification
 * 1.0   05-10-2021   Salesforce Services    Initial Version
 **/
global class SFS_ABNewDayBatchRuleConsumedCapacity implements Database.Batchable<sObject>, Database.Stateful {
    global string query = 'SELECT ID, Slots__c, Active__c,Service_Territory__c,Type__c,Max__c,Day_Of_Week__c,Max_Rule__c,Object__c,Field__c,Value__c,Release_X_Hours_Before__c,Release_X_Hours_Before_Rule__c,Parent_Capacity_Rule_Template__c FROM Capacity_Rule_Template__c WHere Active__c=TRUE AND Type__c=\'Rule Based Capacity\'';
    final string DAYS_TO_BUILD_CAPACITY = 'Days_to_Build_Capacity_Data';
    final string NEW_DAY_RULE_TERRITORY_SIZE = 'NewDayRuleTerritorySize';
    global Set<Id> territorySet;
    global Set<Id> currentTerritorySet;

    public SFS_ABNewDayBatchRuleConsumedCapacity(Set<Id> territoryIdSet) {
        territorySet = new Set<Id>();
        currentTerritorySet = new Set<Id>();
        territorySet = territoryIdSet;
    }

    // Query
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer newDayRuleTerritorySize;
        SFS_AB_Capacity_Settings__mdt appConfig = [
            SELECT Id, Configuration_Name__c, Configuration_Value__c
            FROM SFS_AB_Capacity_Settings__mdt
            WHERE Configuration_Name__c = :NEW_DAY_RULE_TERRITORY_SIZE
        ];
        newDayRuleTerritorySize = Integer.valueOf(appConfig.Configuration_Value__c);
        for (Id territoryId : territorySet) {
            currentTerritorySet.add(territoryId);
        }

        if (currentTerritorySet != null && currentTerritorySet.size() > 0) {
            query = query + ' AND Service_Territory__c IN: currentTerritorySet';
        }

        System.debug(LoggingLevel.debug, 'Started this one');

        return Database.getQueryLocator(query);
    }

    // Execute
    global void execute(Database.BatchableContext BC, List<Capacity_Rule_Template__c> crList) {
        // Vars
        List<Consumed_Capacity__c> ccList = new List<Consumed_Capacity__c>();
        Set<ID> templateIdSet = new Set<ID>();
        Map<String, Consumed_Capacity__c> capTemplateIdToListOfDailyRuleMap = new Map<String, Consumed_Capacity__c>();
        Map<String, Consumed_Capacity__c> existingCapacityRuleMap = new Map<String, Consumed_Capacity__c>();

        // Create Rule based Capacity based on Template + Daily rules that don't exist for the Max days to build
        try {
            // Get the Days to Create and the last date to check
            SFS_AB_Capacity_Settings__mdt appConfig = [
                SELECT Id, Configuration_Name__c, Configuration_Value__c
                FROM SFS_AB_Capacity_Settings__mdt
                WHERE Configuration_Name__c = :DAYS_TO_BUILD_CAPACITY
            ];
            Integer daysToBuild = Integer.valueOf(appConfig.Configuration_Value__c);
            Date lastDate = System.Today().addDays(daysToBuild);
            List<Capacity_Rule_Template__c> parentCapacityRuleList = new List<Capacity_Rule_Template__c>();
            // Get a set of the Template Ids
            for (Capacity_Rule_Template__c cr : crList) {
                templateIdSet.add(cr.Id);
            }

            system.debug('templateIdSet>> ' + templateIdSet);

            // Get the current Rule based to check for gaps and fill them and increment
            for (Consumed_Capacity__c currentRule : [
                SELECT ID, External_Id__c, Capacity_Rule_Template__c,Slots__c
                FROM Consumed_Capacity__c
                WHERE Capacity_Rule_Template__c IN :templateIdSet AND Capacity_Date__c <= :lastDate AND Type__c = 'Rule Based Capacity'
            ]) {
                existingCapacityRuleMap.put(currentRule.External_Id__c, currentRule);
            }

            // Get the associated Daily Rules to parent the rule based against
            for (Consumed_Capacity__c dailyRule : [
                SELECT ID, Service_Territory__c, Capacity_Date__c, Overall_Capacity__c, Capacity_Rule_Template__c,Slots__c
                FROM Consumed_Capacity__c
                WHERE Type__c = 'Daily Capacity' AND Capacity_Date__c <= :lastDate AND Service_Territory__c IN :currentTerritorySet
            ]) {
                String mapKey = dailyRule.Capacity_Rule_Template__c + '-' + dailyRule.Capacity_Date__c.format()+'-'+dailyRule.Slots__c;
                system.debug('mapKey' + mapKey);
                capTemplateIdToListOfDailyRuleMap.put(mapKey, dailyRule);
            }
            system.debug(capTemplateIdToListOfDailyRuleMap.size() + 'capTemplateIdToListOfDailyRuleMap>>>  ' + capTemplateIdToListOfDailyRuleMap);

            for (Capacity_Rule_Template__c cr : crList) {
                if (capTemplateIdToListOfDailyRuleMap != null && capTemplateIdToListOfDailyRuleMap.size() > 0) {
                    for (Integer x = 0; x < daysToBuild; x++) {
                        date mapKeydate = System.today().addDays(x);
                        String localDayofWeek = SFS_ABNewDayBatchDailyConsumedCapacity.getDayOfWeek(mapKeydate);
                        String tempMapKey = cr.Parent_Capacity_Rule_Template__c + '-' + mapKeydate.format()+'-'+cr.Slots__c;
                        system.debug('tempMapKey' + tempMapKey);
                        if (capTemplateIdToListOfDailyRuleMap.containsKey(tempMapKey)) {
                            system.debug('Found the record');
                            Consumed_Capacity__c dRule = capTemplateIdToListOfDailyRuleMap.get(tempMapKey);

                            system.debug('dRule>>> ' + dRule);
                            if (localDayofWeek != null && localDayofWeek == cr.Day_Of_Week__c && cr.Slots__c == dRule.Slots__c) {
                                Consumed_Capacity__c cc = createRuleBasedCapacity(cr, dRule, mapKeydate);
                                if (existingCapacityRuleMap != null && existingCapacityRuleMap.size() > 0 && !existingCapacityRuleMap.containsKey(cc.External_Id__c)) {
                                    system.debug('if>>> ' + cc);
                                    ccList.add(cc);
                                } else if (existingCapacityRuleMap != null && existingCapacityRuleMap.size() == 0) {
                                    system.debug('Else if ' + cc);
                                    ccList.add(cc);
                                }
                            }
                        }
                    }
                }
            }
            system.debug(LoggingLevel.debug, 'ccList>> ' + ccList);
            if (!ccList.isEmpty()) {
                insert ccList;
            }

            System.debug('Heapsize used>' + system.Limits.getHeapSize());
            System.debug('SOQL query rows used>' + System.Limits.getQueryRows());
        } catch (Exception e) {
            System.debug('Exception: ' + e);
        }
    }

    // Fire the New Resource Capacity
    global void finish(Database.BatchableContext BC) {
        territorySet.removeAll(currentTerritorySet);
        if (territorySet.size() > 0) {
            SFS_ABNewDayBatchRuleConsumedCapacity nextIteration = new SFS_ABNewDayBatchRuleConsumedCapacity(territorySet);
            Database.executeBatch(nextIteration, 200);
        } else {
            SFS_ABNewDailyBatchResourceCapacity nextBatch = new SFS_ABNewDailyBatchResourceCapacity();
            Database.executeBatch(nextBatch, 100);
        }
    }

    public static Consumed_Capacity__c createRuleBasedCapacity(Capacity_Rule_Template__c rule, Consumed_Capacity__c dailyRule, Date capacityDate) {
        Consumed_Capacity__c capacity = new Consumed_Capacity__c();

        System.debug(LoggingLevel.DEBUG, 'rule value: ' + rule.Value__c);
        capacity.Object__c = rule.Object__c;
        capacity.Field__c = rule.Field__c;
        capacity.Value__c = rule.Value__c;
        capacity.Max_Rule__c = rule.Max_Rule__c;
        capacity.Parent_Consumed_Capacity__c = dailyRule.Id;
        capacity.Capacity_Rule_Template__c = rule.Id;
        capacity.Slots__c = rule.Slots__c;
        capacity.Service_Territory__c = dailyRule.Service_Territory__c;
        capacity.Release_X_Hours_Before_Rule__c = rule.Release_X_Hours_Before_Rule__c;
        capacity.Type__c = 'Rule Based Capacity';
        capacity.RecordTypeId = Schema.SObjectType.Consumed_Capacity__c.getRecordTypeInfosByDeveloperName().get('Rule_Based_Capacity').getRecordTypeId();
		capacity.External_Id__c = dailyRule.Id + '__' + rule.Id+'__'+rule.Day_of_Week__c+'__'+rule.Value__c+'__'+ dailyRule.Capacity_Date__c.format()+'__'+dailyRule.Slots__c;
        capacity.Capacity_Date__c = capacityDate;
        if (rule.Max_Rule__c != null && dailyRule.Overall_Capacity__c != null) {
            capacity.Overall_Capacity_Rule__c = (rule.Max_Rule__c * 0.01) * dailyRule.Overall_Capacity__c;
        }

        return capacity;
    }
}