force-app/main/default/objects/Capacity_Rule_Template__c/Capacity_Rule_Template__c.object-meta.xml
<CustomObject>
    <label>Capacity Rule Template</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Capacity Rule Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Rule Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Release_X_Hours_Before__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before__c</fullName>
    <label>Release X Hours Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Release_X_Hours_Before_Rule__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before_Rule__c</fullName>
    <label>Release X Hours Before (Rule)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Capacity Rule Templates</relationshipLabel>
    <relationshipName>Capacity_Rule_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Capacity_Rule_Template__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Field__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emergency FFS</fullName>
            </value>
            <value>
                <fullName>Emergency MC</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Part Installs</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Repair FFS</fullName>
            </value>
            <value>
                <fullName>Repair MC</fullName>
            </value>
            <value>
                <fullName>TuneUpAC</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat</fullName>
            </value>
            <value>
                <fullName>TuneUpHeat FFS</fullName>
            </value>
            <value>
                <fullName>TuneUpsAC FFS</fullName>
            </value>
            <value>
                <fullName>Delayed Finish</fullName>
                <isActive>false</isActive>
                <label>Delayed Finish</label>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
                <isActive>false</isActive>
                <label>Delayed Start</label>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
                <isActive>false</isActive>
                <label>Due Date Approaching</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <isActive>false</isActive>
                <label>Low</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Repair</fullName>
                <isActive>false</isActive>
                <label>Repair</label>
            </value>
            <value>
                <fullName>VIP Work</fullName>
                <isActive>false</isActive>
                <label>VIP Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/Consumed_Capacity__c.object-meta.xml
<CustomObject>
    <label>Consumed Capacity</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Consumed Capacity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumed Capacity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumed_Capacity__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(ISPICKVAL(Type__c, &apos;Daily Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before__c), NOW() + (Release_X_Hours_Before__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),IF(ISPICKVAL(Type__c, &apos;Rule Based Capacity&apos;) &amp;&amp; !ISBLANK(Release_X_Hours_Before_Rule__c) ,NOW() + (Release_X_Hours_Before_Rule__c/24) &lt; DATETIMEVALUE(Capacity_Date__c),true))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Date__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Date__c</fullName>
    <label>Capacity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Capacity_Rule_Template__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Rule_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Rule Template</label>
    <referenceTo>Capacity_Rule_Template__c</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work_Type_Category__c</fullName>
                <label>Work Type Category</label>
            </value>
            <value>
                <fullName>FSL__GanttLabel__c</fullName>
                <isActive>false</isActive>
                <label>FSL__GanttLabel__c</label>
            </value>
            <value>
                <fullName>FSL__InJeopardyReason__c</fullName>
                <isActive>false</isActive>
                <label>FSL__InJeopardyReason__c</label>
            </value>
            <value>
                <fullName>Priority</fullName>
                <isActive>false</isActive>
                <label>Priority</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Max_Rule__c.field-meta.xml
<CustomField>
    <fullName>Max_Rule__c</fullName>
    <label>Max % (Rule)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ServiceAppointment</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
                <isActive>false</isActive>
                <label>WorkOrder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Overall_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Overall_Capacity__c</fullName>
    <label>Overall Capacity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Release_X_Hours_Before__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before__c</fullName>
    <label>Release X Hours Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Release_X_Hours_Before_Rule__c.field-meta.xml
<CustomField>
    <fullName>Release_X_Hours_Before_Rule__c</fullName>
    <label>Release X Hours Before (Rule)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Consumed Capacity</relationshipLabel>
    <relationshipName>Consumed_Capacity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <label>Slots</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableSlots</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily Capacity</fullName>
            </value>
            <value>
                <fullName>Rule Based Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Work Type Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Consumed_Capacity__c/recordTypes/Daily_Capacity.recordType-meta.xml
<RecordType>
    <fullName>Daily_Capacity</fullName>
    <active>true</active>
    <description>Create a Daily Consumed Capacity record</description>
    <label>Daily Capacity</label>
</RecordType>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/SFS_AB_Capacity_Settings__mdt.object-meta.xml
<CustomObject>
    <label>SFS AB Capacity Settings</label>
    <pluralLabel>SFS AB Capacity Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SFS_AB_Capacity_Settings__mdt/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/AvailableSlots.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8:00AM - 12:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00PM - 4:00PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00PM - 8:30PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30PM - 10:30PM</fullName>
    </customValue>
    <masterLabel>AvailableSlots</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SFS_ABNewDayBatchDailyConsumedCapacity.cls
/**
 * @description       : To Created daily based CC records based on daily based Capacity_Rule_Template__c records
 * @author            : Ashish Yadav
 * @group             :
 * @last modified on  : 02-14-2021
 * Modifications Log
 * Ver   Date         Author                 Modification
 * 1.0   02-14-2021   Ashish Yadav    Initial Version
 **/
global class SFS_ABNewDayBatchDailyConsumedCapacity implements Database.Batchable<sObject> {
    global string query = 'SELECT ID, Slots__c, Active__c,Service_Territory__c,Type__c,Max__c,Max_Rule__c,Object__c,Field__c,Value__c,Release_X_Hours_Before__c,Release_X_Hours_Before_Rule__c,Day_Of_Week__c,RecordTypeId FROM Capacity_Rule_Template__c WHERE Active__c=TRUE AND Type__c=\'Daily Capacity\'';
    global final string DAYS_TO_BUILD_CAPACITY = 'Days_to_Build_Capacity_Data';

    public SFS_ABNewDayBatchDailyConsumedCapacity()
    {
        
    }
    // Run the query
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    // Execute
    global void execute(Database.BatchableContext BC, List<Capacity_Rule_Template__c> crList) {
        System.debug(crList.size() + '<<crList>> ' + crList);
        System.debug(LoggingLevel.DEBUG, 'debug details');
        capcityLogicExecution(crList);
        
    }
    
    public static void capcityLogicExecution(List<Capacity_Rule_Template__c> crList)
    {
System.debug(' capcityLogicExecution executed');
        // Vars
        Map<String, Consumed_Capacity__c> insertConsumedCapacityMap = new Map<String, Consumed_Capacity__c>();
        Set<ID> templateIdSet = new Set<ID>();
        Map<String, Consumed_Capacity__c> existingCapacityRuleMap = new Map<String, Consumed_Capacity__c>();

        // Create Consumed Capacity Org + Territory "Daily Rules"
        try {
            // Get the Days to Create
            SFS_AB_Capacity_Settings__mdt appConfig = [
                SELECT Id, Configuration_Name__c, Configuration_Value__c
                FROM SFS_AB_Capacity_Settings__mdt
                WHERE Configuration_Name__c = :SFS_ABConstantUtil.DAYS_TO_BUILD_CAPACITY
            ];
            Integer daysToBuild = Integer.valueOf(appConfig.Configuration_Value__c);
            Date lastDate = System.Today().addDays(daysToBuild);
            system.debug('daysToBuild>> ' + daysToBuild);

            // Get a set of the Template Ids
            for (Capacity_Rule_Template__c cr : crList) {
                templateIdSet.add(cr.Id);
            }
            system.debug(templateIdSet.size() + ' templateIdSet>> ' + templateIdSet);

            // Get the current Daily Rules to check for gaps and fill them and increment
            for (Consumed_Capacity__c ccRecord : [
                SELECT ID, External_Id__c, Active__c
                FROM Consumed_Capacity__c
                WHERE Capacity_Rule_Template__c IN :templateIdSet AND Capacity_Date__c <= :lastDate AND Type__c = 'Daily Capacity'
            ]) {
                existingCapacityRuleMap.put(ccRecord.External_Id__c, ccRecord);
            }
            system.debug(existingCapacityRuleMap.size() + ' <<<existingCapacityRuleMap>>> ' + existingCapacityRuleMap);
            // Loop through Capacity Rules and Days -> Insert any days that are missing from now until the max days

            for (Capacity_Rule_Template__c ruleTemplateRecord : crList) {
                for (Integer x = 0; x < daysToBuild; x++) {
                    date mapKeydate = System.today().addDays(x);
                    system.debug('mapKeydate>>>> ' + mapKeydate);
                    //String mapKeyString = ruleTemplateRecord.Organization__c + '-' + ruleTemplateRecord.Service_Territory__c + '-' + mapKeydate.format() + '-' + 'Daily-Capacity';
                    String mapKeyString = ruleTemplateRecord.Service_Territory__c + '-' + mapKeydate.format()+'-'+ ruleTemplateRecord.Slots__c+ '-' + 'Daily-Capacity';

                    String localDayofWeek = getDayOfWeek(mapKeydate);
                    if (string.isNotBlank(localDayofWeek) && ruleTemplateRecord.Day_Of_Week__c == localDayofWeek) {
                        if (existingCapacityRuleMap != null && existingCapacityRuleMap.size() > 0 && !existingCapacityRuleMap.containsKey(mapKeyString)) {
                            system.debug('Key not found>> ' + mapKeyString);
                            Consumed_Capacity__c ccRecord = createCapacity(ruleTemplateRecord, mapKeyString, x);
                            insertConsumedCapacityMap.put(mapKeyString, ccRecord);
                        } else if (existingCapacityRuleMap != null && existingCapacityRuleMap.size() == 0) {
                            system.debug('Map is null');
                            Consumed_Capacity__c ccRecord = createCapacity(ruleTemplateRecord, mapKeyString, x);
                            insertConsumedCapacityMap.put(mapKeyString, ccRecord);
                        }
                    }
                }
            }

            system.debug(insertConsumedCapacityMap.size() + ' <<insertConsumedCapacityMap insert>> ' + insertConsumedCapacityMap);
            if (insertConsumedCapacityMap != null && insertConsumedCapacityMap.size() > 0) {
                insert insertConsumedCapacityMap.values();
                insertConsumedCapacityMap = new Map<String, Consumed_Capacity__c>();
            }

            System.debug('Heapsize used>' + system.Limits.getHeapSize());
            System.debug('SOQL query rows used>' + System.Limits.getQueryRows());
        } catch (Exception e) {
            System.debug('Exception: ' + e);
        }
    }

    // Call the Rule Batch to build the next days rule records associated to the daily rules
    global void finish(Database.BatchableContext BC) {
        System.debug(LoggingLevel.DEBUG, 'in finish');
        for (CronTrigger ct : [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name LIKE '%NewDayBatchDailyCC Job%' AND TimesTriggered != 0]) {
            try {
                //then use the active job id and abort it
                system.abortJob(ct.Id);
            } catch (Exception e) {
                // Handle this exception here
                System.debug('An exception occurred: ' + e.getMessage());
            }
        }
        //List<ServiceTerritory> stList = [SELECT Id from ServiceTerritory WHERE IsActive = TRUE AND TerritoryType__c  != 'DMA'];
        List<ServiceTerritory> stList = [SELECT Id FROM ServiceTerritory WHERE IsActive = TRUE];
        Set<Id> territoryIds = new Set<Id>();
        for (ServiceTerritory st : stList) {
            territoryIds.add(st.Id);
        }
        System.debug('ABOUT TO CALL RULE ONE');
        SFS_ABNewDayBatchRuleConsumedCapacity ruleBatch = new SFS_ABNewDayBatchRuleConsumedCapacity(territoryIds);
        Database.executeBatch(ruleBatch, 200);
        //  SFS_ABNewDailyBatchResourceCapacity nextBatch = new SFS_ABNewDailyBatchResourceCapacity();
        //  Database.executeBatch(nextBatch, 100);
    }

    //Craete Consumed Capacity Record Based on Rule Template
    public static Consumed_Capacity__c createCapacity(Capacity_Rule_Template__c ruleRecord, String mapKey, Integer dayIncrement) {
        Consumed_Capacity__c ccRecord = new Consumed_Capacity__c();
        ccRecord.Capacity_Date__c = System.Today().addDays(dayIncrement);
        ccRecord.Type__c = 'Daily Capacity';
        ccRecord.RecordTypeId = Schema.SObjectType.Consumed_Capacity__c.getRecordTypeInfosByDeveloperName().get('Daily_Capacity').getRecordTypeId();
        if (ruleRecord.Service_Territory__c != null) {
            ccRecord.Service_Territory__c = ruleRecord.Service_Territory__c;
        }
        /*if (ruleRecord.Organization__c != null) {
            ccRecord.Organization__c = ruleRecord.Organization__c;
        }*/
        ccRecord.Max_Rule__c = ruleRecord.Max_Rule__c;
        ccRecord.Release_X_Hours_Before__c = ruleRecord.Release_X_Hours_Before__c;
        ccRecord.Max__c = ruleRecord.Max__c;
        ccRecord.External_Id__c = mapKey;
        ccRecord.Capacity_Rule_Template__c = ruleRecord.Id;
        ccRecord.Overall_Capacity__c = ruleRecord.Max__c;
        ccRecord.Slots__c = ruleRecord.Slots__c;
        return ccRecord;
    }

    //To get Day of Week from Date
    public static String getDayOfWeek(Date dt) {
        DateTime myDateTime = (DateTime) dt.addDays(1);
        String dayOfWeek = myDateTime.format('EEEE');
        return dayOfWeek;
    }
}